services:
  build: formationsServices
  volumes:
   - formationsServices:/app
  ports:
   - "8090:3000"
ihm:
  build: formationsIhm
  volumes:
   - formationsIhm/src/main/webapp:/app
  ports:
   - "8080:80"
  links:
   - services:services
ihmmobile:
  build: formationsIhmIonic
  volumes:
   - formationsIhmIonic/www:/app
  ports:
   - "8081:80"
  links:
   - services:services
