services:
  build: formationsServices
  volumes:
   - formationsServices:/app
  ports:
   - "8090:3000"
ambassador:
  image: cpuguy83/docker-grand-ambassador
  links:
    - services:services
ihm:
  build: formationsIhm
  volumes:
   - formationsIhm/src/main/webapp:/app
  ports:
   - "8080:80"
  links:
   - ambassador:services
ihmmobile:
  build: formationsIhmIonic
  volumes:
   - formationsIhmIonic/www:/app
  ports:
   - "8081:80"
  links:
   - ambassador:services
