#%RAML 0.8

title: Gestion des formations softeam

schemas:
  - formations: !include schema/formations.json
    formation: !include schema/formation.json

/formations:
  get: 
    queryParameters:
      categorie:
        type: string
    responses:
      200:
        body:
          application/json:
            schema: formations